### ISSUE TITLE
fez random_command throws a long stacktrace

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#23]
```
/Users/philc/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:311:in `block in mandatory': Please specify the server domain via the :domain variable (Rake::ConfigurationError)
from /Users/philc/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:268:in `call'
from /Users/philc/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:268:in `block in fetch'
```

**Comment by philc** [comment]
Sorry, this is because I'm using a super old version of fezzik.
