### ISSUE TITLE
Fezzik triggers deprecation warnings in Rake 0.9.6

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#46]
```
$ bundle exec rake howdy

WARNING: Global access to Rake DSL methods is deprecated.  Please include
    ...  Rake::DSL into classes and modules which use the Rake DSL methods.
WARNING: DSL method Module#import called at /Users/reformist/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fezzik-0.7.4/lib/fezzik/base.rb:10:in `block in init'
WARNING: DSL method Module#import called at /Users/reformist/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fezzik-0.7.4/lib/fezzik/base.rb:10:in `block in init'
WARNING: DSL method Module#import called at /Users/reformist/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fezzik-0.7.4/lib/fezzik/base.rb:10:in `block in init'
```

**Comment by dmac** [comment]
A vanilla install of fezzik 0.7.4 and rake 0.9.6 with a clean Rakefile doesn't manifest this problem for me. Is it possible you were using an older fezzik version, or that your Rakefile or .rake files include rake DSL commands?
